name: Configurar Active Directory y usuarios
on: workflow_dispatch

jobs:
  configurar-ad:
    runs-on: ubuntu-latest
    environment: secrets
    permissions:
      contents: write
    env:
      RG: ACTIVE_DIR
      VM: RedesAD
      ADMIN_USER: azureuser
      ADMIN_PASSWORD: 'ClaveSegura123!'
      DOMAIN: redes1.dev

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Promover a DC y crear usuarios
      uses: azure/cli@v2
      with:
        inlineScript: |
          echo "🔎 Obteniendo IP de la VM..."
          VM_IP=$(az vm show -d -g "$RG" -n "$VM" --query publicIps -o tsv)
          echo "📡 IP encontrada: $VM_IP"

          echo "🚀 Ejecutando PowerShell remoto para configurar Active Directory..."

          az vm run-command invoke \
            --resource-group "$RG" \
            --name "$VM" \
            --command-id RunPowerShellScript \
            --scripts '
              $domain = "${{ env.DOMAIN }}"
              $adminPass = "${{ env.ADMIN_PASSWORD }}"
              $securePass = ConvertTo-SecureString $adminPass -AsPlainText -Force

              Install-WindowsFeature AD-Domain-Services -IncludeManagementTools
              Import-Module ADDSDeployment

              Install-ADDSForest `
                  -DomainName $domain `
                  -CreateDnsDelegation:$false `
                  -DatabasePath "C:\Windows\NTDS" `
                  -DomainMode "Win2012R2" `
                  -DomainNetbiosName ($domain.Split(".")[0]) `
                  -ForestMode "Win2012R2" `
                  -InstallDns:$true `
                  -LogPath "C:\Windows\NTDS" `
                  -SysvolPath "C:\Windows\SYSVOL" `
                  -Force:$true `
                  -SafeModeAdministratorPassword $securePass

              Start-Sleep -Seconds 60

              $userPass = ConvertTo-SecureString "holaholaholahola12+" -AsPlainText -Force

              New-ADUser -Name "usuario final" -GivenName "usuario" -Surname "final" -UserPrincipalName "usuario@$domain" -AccountPassword $userPass -Enabled $true

              1..4 | ForEach-Object {
                New-ADUser -Name "usuario$_" -SamAccountName "usuario$_" -UserPrincipalName "usuario$_@$domain" -AccountPassword $userPass -Enabled $true
              }

              Write-Output "✅ Active Directory configurado y usuarios creados en $domain"
            '
