name: Actualizar IP LDAP
on:
  workflow_dispatch:

jobs:
  update-php:
    runs-on: ubuntu-latest
    environment: secrets
    permissions:
      contents: write   # Necesario para hacer commit & push

    env:
      RG: ACTIVE_DIR    # Resource Group donde vive la VM
      VM: RedesAD       # Nombre de tu VM en Azure

    steps:
      # 1. Traer todo el repo y su historial para poder hacer pull y push
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. Autenticar con Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Obtener la IP pública de la VM y guardarla en VM_IP
      - name: Obtener IP pública
        id: getip
        uses: azure/cli@v2
        with:
          inlineScript: |
            IP=$(az vm show -g "$RG" -n "$VM" -d --query publicIps -o tsv)
            echo "VM_IP=$IP" >> $GITHUB_ENV
            echo "Encontrada IP pública: $IP"

      # 4. Sincronizar main para partir de la última versión
      - name: Sincronizar main
        run: git pull origin main

      # 5. Reemplazar la antigua IP por la nueva en php/login.php
      - name: Actualizar ldap_server en login.php
        run: |
          FILE="php/login.php"
          OLD_IP=$(grep -oE 'ldap://[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' "$FILE" | cut -d/ -f3 | head -n1 || true)
          NEW_IP="${{ env.VM_IP }}"
          echo "IP actual en login.php: ${OLD_IP:-<no encontrada>}"
          echo "IP obtenida de la VM: $NEW_IP"

          if [[ "$OLD_IP" != "$NEW_IP" ]]; then
            sed -E -i "s|(ldap://)[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+|\1$NEW_IP|" "$FILE"
            echo "✔️  login.php actualizado con la nueva IP."
          else
            echo "ℹ️  La IP no cambió; no se realizaron modificaciones."
          fi

      # 6. Commit & Push del cambio
      - name: Commit y push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add php/login.php
          if git diff --cached --quiet; then
            echo "ℹ️  Sin cambios para commitear."
          else
            git commit -m "ci: update LDAP IP -> ${{ env.VM_IP }}"
            git push origin HEAD:main
          fi
