name: Actualizar IP LDAP
on: workflow_dispatch

jobs:
  update-php:
    runs-on: ubuntu-latest
    environment: secrets
    permissions:
      contents: write          # para commit/push

    env:
      RG: ACTIVE_DIR           # ← Resource Group donde vive la VM
      VM: RedesAD              # ← Nombre exacto de la VM

    steps:
    # 1. Código
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }

    # 2. Login a Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # 3. Obtener la IP pública de la VM
    - name: Obtener IP pública
      id: getip
      uses: azure/cli@v2
      with:
        inlineScript: |
          IP=$(az vm show -g "$RG" -n "$VM" -d --query publicIps -o tsv)
          echo "public_ip=$IP" >> $GITHUB_OUTPUT
          echo "VM_IP=$IP"     >> $GITHUB_ENV
          echo "Encontrada IP: $IP"

    # 4. Sustituir IP en login.php
    # ─── OPCIÓN A: marcador fijo ─────────
    - name: Reemplazar marcador
      run: |
        sed -i "s|ldap://REPLACE_WITH_IP|ldap://${{ env.VM_IP }}|" php/login.php

    # ─── OPCIÓN B: sustituir cualquier IP ─
    # Descomenta si prefieres detectar cualquier IPv4
    # - run: |
    #     sed -E -i "s|(ldap://)[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+|\1${{ env.VM_IP }}|" php/login.php

    # 5. Commit y push
    - name: Commit y push
      run: |
        git config user.name  "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add php/login.php
        git commit -m "ci: update LDAP IP -> ${{ env.VM_IP }}" || echo "Sin cambios"
        git pull --rebase --autostash
        git push
